[font]
normal = { family = "Hackgen Console", style = "Regular" }
bold = { family = "Hackgen Console", style = "Bold" }
italic = { family = "Hackgen Console", style = "Italic" }
size = 10

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
opacity = 0.9

[mouse]
hide_when_typing = true
