[tools]
node = 'latest'
deno = 'latest'
bun = 'latest'
pnpm = 'latest'
rust = 'latest'
'npm:@google/gemini-cli' = 'latest'
'aqua:LuaLS/lua-language-server' = 'latest'
"github:sqls-server/sqls" = "latest"

[settings]
trusted_config_paths = [
    "~/dotfiles/mise/config.toml"
]
